version: "3.8"

services:
  rabbit:
    image: rabbitmq:3.12.13-management-alpine
    hostname: "rabbit"
    environment:
      - RABBITMQ_DEFAULT_USER=user
      - RABBITMQ_DEFAULT_PASS=password

  producer:
    build:
      context: .
      dockerfile: Dockerfile
    command: python producer.py
    ports:
      - "80:80"
    depends_on:
      - rabbit
    restart: always
    volumes:
      - ".:/opt:ro"

  consumer:
    build:
      context: .
      dockerfile: Dockerfile
    command: faststream run consumer:app
    depends_on:
      - rabbit
    restart: always
    volumes:
      - ".:/opt:ro"